kind: ConfigMap
apiVersion: v1
metadata:
  name: scylladb-servers-configmap
  namespace: prod-internal
data:
  SCYLLA_SERVERS: scylla.internal.premfina.com
  SCYLLA_REPLICATION_STRATEGY: "{'class': 'NetworkTopologyStrategy', 'datacenter1' : 3}"
  SCYLLA_TIMEOUT: '10000ms'
  SCYLLA_CONNECT_TIMEOUT: '10000ms'
   
