kind: ConfigMap
apiVersion: v1
metadata:
  name: scylladb-servers-configmap
  namespace: prod-internal
data:
  SCYLLA_SERVERS: scylla.internal.premfina.com
  GLOBAL_SCYLLA_SERVERS: scylla-global.internal.premfina.com
  SCYLLA_REPLICATION_STRATEGY: "{'class': 'NetworkTopologyStrategy', 'PF-UK-DC1' : 3}"
  SCYLLA_ENCRYPTION_KEY: 'nil'
  SCYLLA_SSL: 'nil'
  SCYLLA_TIMEOUT: '10000'
  SCYLLA_CONNECT_TIMEOUT: '10000'
  SCYLLA_DEFAULT_PAGE_SIZE: '10'
