kind: ConfigMap
apiVersion: v1
metadata:
  name: services-configmap
  namespace: prod-internal
data:
  PF_INSURER_PRICING_ENGINE_SERVICE_HOSTNAME: "be-insurer-pricing-engine-svc"
  PF_USER_MANAGER_SERVICE_HOSTNAME: "be-user-manager-svc"
  PF_GLOBAL_WORKSPACE_AUTH_SERVICE_HOSTNAME: "be-global-workspace-auth-svc"
  PF_OCR_READER_SERVICE_HOSTNAME: "be-ocr-reader-svc"
  PF_FILE_MANAGER_SERVICE_HOSTNAME: "http://be-file-manager.internal.premfina.com"
  PF_BANK_CHECKER_EXPERIAN_SERVICE_HOSTNAME: "http://be-bank-checker-experian-svc"
  # PF_CUSTOMER_PORTAL_HOST: "http://be-customers-api.internal.premfina.com"
  PF_CUSTOMER_PORTAL_HOST: "http://10.4.3.6:7080"
  PF_PAYMENTS_STRIPE_SERVICE_URL: "http://be-payments-stripe.internal.premfina.com"
  PF_DATA_FETCHER_ORACLE_SERVICE_HOSTNAME: "http://be-data-fetcher-oracle.internal.premfina.com"
  PF_SLACK_NOTIFICATIONS_SERVICE_HOSTNAME: "http://be-slack-notifications.internal.premfina.com"
  PF_CLE_API_APISUPER_SERVICE_HOSTNAME_TPFPROD1: "http://cle-api-pf-prod-p.services.premfina.com"
  PF_EMAIL_SERVICE_HOSTNAME: "http://be-email.internal.premfina.com"
  PF_CRA_EXPERIAN_SERVICE_HOSTNAME: "http://10.4.0.7:8027"
  PF_CRA_CREDIT_SAFE_SERVICE_HOSTNAME: "http://10.4.0.7:8044"
  PF_CRA_LEXIS_NEXIS_SERVICE_HOSTNAME: "https://be-cra-lexisnexis.internal.premfina.com"
  PF_AFFORDABILITY_HOSTNAME: "http://be-affordability.internal.premfina.com"
  PF_ID_UPLOAD_HOSTNAME: "be-id-upload.internal.premfina.com:443"
  PF_AGREEMENT_FILES_SERVICE_HOSTNAME: "http://10.4.0.7:8017"  # We don't have a DNS for this service
