kind: ConfigMap
apiVersion: v1
metadata:
  name: common-configmap
  namespace: dev-internal
data:
  GRPC_SSL_HOST_PORT: 0.0.0.0:443
  GRPC_HOST_PORT: 0.0.0.0:80
  REST_SSL_HOST_PORT: 0.0.0.0:8443
  REST_HOST_PORT: 0.0.0.0:8080  
  IDENTITIES_SERVICE_HOSTNAME: "be-db-identities-svc:443"
  USER_MANAGER_SERVICE_HOSTNAME: "be-user-manager-svc:443"
  API_KEY_HEADER_AUTHORIZATION: "x-api-key"
  JTW_EXPIRATION_TIME_IN_MINUTES: "15"
  JWT_AUTHORIZATION: "pf-authorization"
