kind: ConfigMap
apiVersion: v1
metadata:
  name: scylladb-servers-configmap
  namespace: dev-internal
data:
  SCYLLA_SERVERS: scylla.internal.dev.premfina.com
  PUBLIC_SCYLLA_SERVERS: scylla-public.internal.dev.premfina.com
  SCYLLA_REPLICATION_STRATEGY: "{'class': 'NetworkTopologyStrategy', 'datacenter1' : 1}"
  SCYLLA_TIMEOUT: '10000'
  SCYLLA_CONNECT_TIMEOUT: '10000'