kind: ConfigMap
apiVersion: v1
metadata:
  name: scylladb-servers-configmap
  namespace: dev-internal
data:
  SCYLLA_SERVERS: scylla.internal.dev.premfina.com
  REPLICATION_CLASS: NetworkTopologyStrategy
  DATA_CENTERS: 'datacenter1'
  REPLICATION_FACTOR: '1'
   
