kind: ConfigMap
apiVersion: v1
metadata:
  name: shared-storage-mountpoints-configmap
  namespace: dev-internal
data:
  PF_CRA_REPORT_SHARED_STORAGE_PATH: "/mnt/pfdevukfilestorage/dev-system-files/be__cra/cra_report"
